app_name: solar_ingestion

database:
  #connection_string: "DRIVER={ODBC Driver 17 for SQL Server};SERVER=10.48.184.166;DATABASE=SolarDataDB;UID=sa;PWD=p@ssw0rd;TrustServerCertificate=yes;"
  connection_string: "DRIVER={ODBC Driver 18 for SQL Server};SERVER=SOLAR-DB\\SOLARSQL;DATABASE=SolarDataDB;UID=sa;PWD=p@ssw0rd;Encrypt=yes;TrustServerCertificate=yes;"

storage:
  raw_root: "C:/SOLAR/DATA/raw"

timezone:
  local_tz_name: "Asia/Bangkok"

api:
  timeout_seconds: 120
  account_min_interval_seconds: 60

retry:
  max_attempts: 3
  backoff_seconds: 5

scheduler:
  rate_limit_backoff_seconds:
    first: 120
    second: 300
    third: 900

cooldown:
  rate_limit_minutes: 10
  login_fail_minutes: 30

pipeline:
  generic_metrics:
    enabled: false
    normalize_chunk_size: 5000
    pending_limit: 100

test:
  base_url: "https://sg5.fusionsolar.huawei.com"
  username: "GPSC_PI_03"
  api_password: "pi@dmin1"

  station_codes:
    - "NE=50281829"

  dev_type_id: 1
  dev_ids:
    - 1234567890123
    - 1234567890456